# Configuración general
spring.application.name=pago.servicios
server.port=8081

# Base de datos relacional (Supabase PostgreSQL - Session Pooler IPv4)
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.undroqmyeoprnqauqufz
spring.datasource.password=ds48TELpYAEaFrRI
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.data-source-properties.prepareThreshold=0

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JDBC batch
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

# Base de datos NoSQL (MongoDB Atlas)
spring.data.mongodb.uri=mongodb+srv://aguayomar77_db_user:qN8jN2yJeIM5YPPd@gestopago.t6cohep.mongodb.net/gestopago?appName=GestoPago

# Token de Copomex ()
copomex.api.token=pruebas

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Configuración del Servicio Externo
external.service.token=qmzAAEYFmqQbIT/Ktxme8FDV343iYQPwVJM4T39cEinWq1yjc1pp9oxSo4Rjmo5Fk27YzkCDaCr5RM4xtGZNCBZk1MH1tMNbykJ/WzfVjxSEXc9FERnZJPsVuFcAgfsfHmEYEfsLSmLZgovuGmnpDA==
api.gestopago.com=/sistema/service/getProductList.do
# Endpoint de GetProductList en Gestopago
gestopago.service.getProductList=/sistema/service/getProductList.do
gestopago.auth.url=https://gestopago.portalventas.net
gestopago.auth.id-distribuidor=83
gestopago.auth.codigo-dispositivo=GPS83-TPV-17
gestopago.auth.password=12345678
service.externo.timeout.connect=5000
service.externo.timeout.read=5000

spring.cloud.config.import-check.enabled=false